Repository texasexes/d8-theme-main, pull requests merged in 2018-07, with the labels that each got.

#8 Mega Menu
  components/_patterns/02-molecules/02-menu/_01-nav-base.scss
  components/_patterns/02-molecules/02-menu/_primary-nav.scss
  components/_patterns/02-molecules/menus/_menu-item.twig
  components/_patterns/02-molecules/menus/_menu.twig
  components/_patterns/02-molecules/menus/main-menu/_main-menu.scss
  components/_patterns/02-molecules/menus/main-menu/main-menu.js
  components/_patterns/02-molecules/menus/main-menu/main-menu.twig
  components/_patterns/02-molecules/menus/main-menu/main-menu.yml
  dist/02-molecules/menus/main-menu/main-menu.js
  dist/02-molecules/menus/main-menu/main-menu.js.map
  dist/scripts-styleguide.js
  dist/scripts-styleguide.js.map
  dist/style.css
  dist/style.css.map
  templates/navigation/fields/field--menu-link-content--field-txex-ref-rev-para-01d.html.twig
  templates/navigation/primary-nav/menu--extras--txex-main--header.html.twig
  templates/navigation/primary-nav/menu--extras--txex-main.html.twig
  templates/navigation/primary-nav/menu--extras.html.twig
  templates/navigation/primary-nav/menu-levels--txex-main.html.twig
  templates/navigation/primary-nav/menu-levels.html.twig
  templates/navigation/primary-nav/menu-link-content--txex-main.html.twig
  yarn.lock
Labels: ready for review

#13 Accordion styles
  components/_patterns/00-base/global/01-colors/_color-vars.scss
  components/_patterns/00-base/global/01-colors/colors.yml
  components/_patterns/02-molecules/accordion/_accordion.scss
  components/_patterns/02-molecules/accordion/accordion.js
  components/_patterns/02-molecules/accordion/accordion.twig
  components/_patterns/02-molecules/accordion/accordion.yml
  dist/02-molecules/accordion/accordion.js
  dist/02-molecules/accordion/accordion.js.map
  dist/scripts-styleguide.js
  dist/scripts-styleguide.js.map
  dist/style.css
  dist/style.css.map
Labels: ready for review

#14 connected accordion styles to paragraph templates
  d8_theme_main.libraries.yml
  templates/paragraphs/txex_paragraph_42/paragraph--txex-paragraph-42.html.twig
  templates/paragraphs/txex_paragraph_43/paragraph--txex-paragraph-43.html.twig
Labels: reviewed with comments

#15 Navigation fix
  components/_patterns/02-molecules/02-menu/_main-navigation.scss
  components/_patterns/02-molecules/04-page-title/_page-title.scss
  components/_patterns/02-molecules/menus/main-menu/_main-menu.scss
  components/_patterns/03-organisms/04-chapter/_chapter.scss
  d8_theme_main.info.yml
  dist/style.css
  dist/style.css.map
  templates/base_overrides/layout/page.html.twig
  templates/layout/regions/region--content-top.html.twig
  templates/layout/regions/region--main-navigation.html.twig
Labels: ready for review, required by main repo pr

#19 Add sideburns color to outer edges of the page
  components/_patterns/00-base/global/01-colors/_color-vars.scss
  components/_patterns/00-base/global/01-colors/colors.yml
  components/_patterns/00-base/global/base/_base.scss
  components/_patterns/00-base/layouts/layout/_layout.scss
  components/_patterns/03-organisms/site/header/_content-top.scss
  components/_patterns/03-organisms/site/header/_header.scss
  dist/style.css
  dist/style.css.map
Labels: ready for review

#18 Scholarship person
  components/_patterns/00-base/global/01-colors/_colors-used.scss
  components/_patterns/00-base/global/base/_02-breakpoints.scss
  components/_patterns/01-atoms/01-links/link/_link.scss
  components/_patterns/01-atoms/03-text/_text.scss
  components/_patterns/01-atoms/03-text/_text.twig
  components/_patterns/01-atoms/04-images/00-image/00-image.twig
  components/_patterns/01-atoms/04-images/00-image/_image.scss
  components/_patterns/02-molecules/01-card/_not-used/16-card~landscape-wide-50-1-column.yml.unused
  components/_patterns/02-molecules/person-card/_person-card.scss
  components/_patterns/02-molecules/person-card/_person-card.twig
  components/_patterns/02-molecules/person-card/person-card--advocate.twig
  components/_patterns/02-molecules/person-card/person-card--advocate.yml
  components/_patterns/02-molecules/person-card/person-card--scholarship.twig
  components/_patterns/02-molecules/person-card/person-card--scholarship.yml
  components/_patterns/02-molecules/person-card/person-card--teaser.twig
  components/_patterns/02-molecules/person-card/person-card--teaser.yml
  components/_patterns/03-organisms/card-list/_card-list.twig
  components/_patterns/03-organisms/card-list/person-list.twig
  components/_patterns/03-organisms/card-list/person-list.yml
  dist/style.css
  dist/style.css.map
  templates/nodes/person/node--person-scholarship-recipient--default.html.twig
Labels: ready for review, required by main repo pr

#20 Fix sidebar nav
  dist/style.css
  dist/style.css.map
  templates/blocks/block--txexmainnavigation.html.twig
  templates/navigation/primary-nav/menu--extras.html.twig
  templates/navigation/primary-nav/menu-levels.html.twig
Labels: ready for review

#21 Mobilize everything
  components/_patterns/00-base/layouts/01-base/_d_layout.scss
  components/_patterns/00-base/layouts/item/_absolute__item.scss
  components/_patterns/00-base/layouts/item/_flexbox__item.scss
  components/_patterns/00-base/layouts/item/_item.scss
  components/_patterns/00-base/layouts/layout/__layout--pl.scss
  components/_patterns/00-base/layouts/layout/_layout.scss
  dist/style.css
  dist/style.css.map
  templates/paragraphs/txex_paragraph_22/paragraph--txex-paragraph-22.html.twig
Labels: ready for review

#22 Scholars view
  components/_patterns/01-atoms/03-text/_text.scss
  components/_patterns/02-molecules/person-card/_person-card.twig
  components/_patterns/03-organisms/card-list/person-list.yml
  components/_patterns/03-organisms/grid/_grid.scss
  components/_patterns/03-organisms/grid/_grid.twig
  components/_patterns/03-organisms/grid/card-grid.twig
  components/_patterns/03-organisms/grid/card-grid.yml
  dist/style.css
  dist/style.css.map
  package-lock.json
  templates/nodes/person/node--person-scholarship-recipient--teaser.html.twig
  templates/views/views-view--scholars.html.twig
  templates/views/views-view-unformatted--scholars.html.twig
  templates/views/viewsreference--view-title--scholars.html.twig
Labels: ready for review, required by main repo pr

#27 Fixed sidebar nav overflow and indention.
  components/_patterns/02-molecules/02-menu/_sidebar-nav.scss
  dist/style.css
  dist/style.css.map
Labels: ready for review

#28 Theme Login Form
  components/_patterns/00-base/global/01-colors/_color-vars.scss
  components/_patterns/00-base/global/01-colors/colors.yml
  components/_patterns/00-base/global/base/_03-mixins.scss
  components/_patterns/01-atoms/02-form_elements/01-button/00-button~small.yml
  components/_patterns/01-atoms/02-form_elements/01-button/_button.scss
  components/_patterns/01-atoms/02-form_elements/02-input/_input.scss
  components/_patterns/03-organisms/login/_login.scss
  d8_theme_main.theme
  dist/style.css
  dist/style.css.map
  templates/base_overrides/layout/page--user.html.twig
  templates/base_overrides/layout/page.html.twig
  templates/forms/form--user-login-form.html.twig
Labels: ready for review
